# Generated by Django 5.1.4 on 2024-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_completed',
            field=models.BooleanField(default=False),
        ),
    ]
